# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - africare-backend

on:
  push:
    branches:
      - newbranch-azure-deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Install Dependencies
        run: npm install
      - name: Deploy to azure App service
        uses: azure/webapps-deploy@v2
        with:
          app-name: backend-africare
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_06F5DDC8582F42488DF4144B201A0799 }}
           package: .